
with seeded_edges as (
  select *
  from (
    values
      ('edge:gt-apply'::text, 'table:public.conversation_spans'::text, 'reads'::text,
        '{"seeded": true, "seed_source": "trust_primitives_step4_20260223"}'::jsonb),
      ('edge:gt-apply', 'table:public.projects', 'reads',
        '{"seeded": true, "seed_source": "trust_primitives_step4_20260223"}'),
      ('edge:gt-apply', 'table:public.span_attributions', 'writes',
        '{"seeded": true, "seed_source": "trust_primitives_step4_20260223"}'),
      ('edge:gt-apply', 'table:public.override_log', 'writes',
        '{"seeded": true, "seed_source": "trust_primitives_step4_20260223"}'),
      ('edge:gt-apply', 'table:public.evidence_events', 'writes',
        '{"seeded": true, "seed_source": "trust_primitives_step4_20260223"}'),
      ('edge:alias-hygiene', 'table:public.project_aliases', 'reads',
        '{"seeded": true, "seed_source": "trust_primitives_step4_20260223"}'),
      ('edge:alias-hygiene', 'table:public.projects', 'reads',
        '{"seeded": true, "seed_source": "trust_primitives_step4_20260223"}'),
      ('edge:alias-hygiene', 'table:public.suggested_aliases', 'reads',
        '{"seeded": true, "seed_source": "trust_primitives_step4_20260223"}'),
      ('edge:alias-hygiene', 'table:public.project_aliases', 'writes',
        '{"seeded": true, "seed_source": "trust_primitives_step4_20260223"}'),
      ('edge:alias-hygiene', 'table:public.suggested_aliases', 'writes',
        '{"seeded": true, "seed_source": "trust_primitives_step4_20260223"}'),
      ('edge:alias-review', 'table:public.suggested_aliases', 'reads',
        '{"seeded": true, "seed_source": "trust_primitives_step4_20260223"}'),
      ('edge:alias-review', 'table:public.projects', 'reads',
        '{"seeded": true, "seed_source": "trust_primitives_step4_20260223"}'),
      ('edge:alias-review', 'table:public.project_aliases', 'reads',
        '{"seeded": true, "seed_source": "trust_primitives_step4_20260223"}'),
      ('edge:alias-review', 'table:public.project_aliases', 'writes',
        '{"seeded": true, "seed_source": "trust_primitives_step4_20260223"}'),
      ('edge:alias-review', 'table:public.suggested_aliases', 'writes',
        '{"seeded": true, "seed_source": "trust_primitives_step4_20260223"}'),
      ('edge:alias-scout', 'table:public.projects', 'reads',
        '{"seeded": true, "seed_source": "trust_primitives_step4_20260223"}'),
      ('edge:alias-scout', 'table:public.project_aliases', 'reads',
        '{"seeded": true, "seed_source": "trust_primitives_step4_20260223"}'),
      ('edge:alias-scout', 'table:public.suggested_aliases', 'reads',
        '{"seeded": true, "seed_source": "trust_primitives_step4_20260223"}'),
      ('edge:alias-scout', 'table:public.span_attributions', 'reads',
        '{"seeded": true, "seed_source": "trust_primitives_step4_20260223"}'),
      ('edge:alias-scout', 'table:public.conversation_spans', 'reads',
        '{"seeded": true, "seed_source": "trust_primitives_step4_20260223"}'),
      ('edge:alias-scout', 'table:public.contacts', 'reads',
        '{"seeded": true, "seed_source": "trust_primitives_step4_20260223"}'),
      ('edge:alias-scout', 'table:public.suggested_aliases', 'writes',
        '{"seeded": true, "seed_source": "trust_primitives_step4_20260223"}'),
      ('edge:embed-facts', 'table:public.project_facts', 'reads',
        '{"seeded": true, "seed_source": "trust_primitives_step4_20260223"}'),
      ('edge:embed-facts', 'table:public.project_facts', 'writes',
        '{"seeded": true, "seed_source": "trust_primitives_step4_20260223"}'),
      ('edge:evidence-assembler', 'table:public.span_attributions', 'reads',
        '{"seeded": true, "seed_source": "trust_primitives_step4_20260223"}'),
      ('edge:evidence-assembler', 'table:public.conversation_spans', 'reads',
        '{"seeded": true, "seed_source": "trust_primitives_step4_20260223"}'),
      ('edge:evidence-assembler', 'table:public.project_contacts', 'reads',
        '{"seeded": true, "seed_source": "trust_primitives_step4_20260223"}'),
      ('edge:evidence-assembler', 'table:public.correspondent_project_affinity', 'reads',
        '{"seeded": true, "seed_source": "trust_primitives_step4_20260223"}'),
      ('edge:evidence-assembler', 'table:public.journal_claims', 'reads',
        '{"seeded": true, "seed_source": "trust_primitives_step4_20260223"}'),
      ('edge:evidence-assembler', 'table:public.project_facts', 'reads',
        '{"seeded": true, "seed_source": "trust_primitives_step4_20260223"}'),
      ('edge:evidence-assembler', 'table:public.review_queue', 'reads',
        '{"seeded": true, "seed_source": "trust_primitives_step4_20260223"}'),
      ('edge:admin-reseed', 'table:public.conversation_spans', 'reads',
        '{"seeded": true, "seed_source": "trust_primitives_step4_20260223"}'),
      ('edge:admin-reseed', 'table:public.span_attributions', 'reads',
        '{"seeded": true, "seed_source": "trust_primitives_step4_20260223"}'),
      ('edge:admin-reseed', 'table:public.override_log', 'reads',
        '{"seeded": true, "seed_source": "trust_primitives_step4_20260223"}'),
      ('edge:admin-reseed', 'table:public.interactions', 'reads',
        '{"seeded": true, "seed_source": "trust_primitives_step4_20260223"}'),
      ('edge:admin-reseed', 'table:public.conversation_spans', 'writes',
        '{"seeded": true, "seed_source": "trust_primitives_step4_20260223"}'),
      ('edge:admin-reseed', 'table:public.span_attributions', 'writes',
        '{"seeded": true, "seed_source": "trust_primitives_step4_20260223"}'),
      ('edge:admin-reseed', 'table:public.override_log', 'writes',
        '{"seeded": true, "seed_source": "trust_primitives_step4_20260223"}'),
      ('edge:admin-reseed', 'table:public.striking_signals', 'writes',
        '{"seeded": true, "seed_source": "trust_primitives_step4_20260223"}'),
      ('edge:admin-reseed', 'table:public.journal_claims', 'writes',
        '{"seeded": true, "seed_source": "trust_primitives_step4_20260223"}'),
      ('edge:admin-reseed', 'table:public.review_queue', 'writes',
        '{"seeded": true, "seed_source": "trust_primitives_step4_20260223"}'),
      ('edge:admin-reseed', 'edge:context-assembly', 'calls',
        '{"seeded": true, "seed_source": "trust_primitives_step4_20260223"}'),
      ('edge:admin-reseed', 'edge:ai-router', 'calls',
        '{"seeded": true, "seed_source": "trust_primitives_step4_20260223"}'),
      ('edge:admin-reseed', 'edge:striking-detect', 'calls',
        '{"seeded": true, "seed_source": "trust_primitives_step4_20260223"}'),
      ('edge:admin-reseed', 'edge:journal-extract', 'calls',
        '{"seeded": true, "seed_source": "trust_primitives_step4_20260223"}')
  ) as t(from_node_id, to_node_id, edge_type, meta)
)
insert into public.system_lineage_edges (
  from_node_id, to_node_id, edge_type,
  first_seen_at_utc, last_seen_at_utc, seen_count, meta
)
select
  from_node_id, to_node_id, edge_type,
  now(), now(), 1, meta
from seeded_edges
on conflict (from_node_id, to_node_id, edge_type)
do update set
  last_seen_at_utc = greatest(public.system_lineage_edges.last_seen_at_utc, excluded.last_seen_at_utc),
  seen_count = greatest(public.system_lineage_edges.seen_count, 1),
  meta = coalesce(public.system_lineage_edges.meta, '{}'::jsonb)
    || coalesce(excluded.meta, '{}'::jsonb);
;
